name: develop

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: Make
        run: ./cmd/develop.sh
      - name: Test
        run: go test -v -p 1 ./...
