name: develop

on:
  pull_request:
  push:

jobs:
  develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: Make
        run: cmd/develop.sh
      - name: Test
        run: go test -v -p 1 ./...
